services:
  main-db:
    image: postgres:16
    environment:
      POSTGRES_USER: main_user
      POSTGRES_PASSWORD: main_pass
      POSTGRES_DB: main_db
    ports:
      - "5433:5432"
    volumes:
      - ./main-service/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U main_user -d main_db"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  main-service:
    build:
      context: .
      dockerfile: ./main-service/Dockerfile
    environment:
      DATABASE_URL: postgres://main_user:main_pass@main-db:5432/main_db?sslmode=disable
      JWT_SECRET: dev-secret-change
      POSTS_SERVICE_ADDR: posts-service:50051
      KAFKA_BROKERS: kafka:9092
      KAFKA_VIEWS_TOPIC: post_views
      KAFKA_LIKES_TOPIC: post_likes
    depends_on:
      main-db:
        condition: service_healthy
      posts-service:
        condition: service_started
      kafka:
        condition: service_started
    ports:
      - "8080:8080"

  posts-mongo:
    image: mongo:7
    ports:
      - "27018:27017"

  posts-service:
    build:
      context: .
      dockerfile: ./posts-service/Dockerfile
    environment:
      GRPC_ADDR: ":50051"
      MONGO_URI: mongodb://posts-mongo:27017
    depends_on:
      - posts-mongo
    ports:
      - "50051:50051"

  zookeeper:
    image: bitnamilegacy/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnamilegacy/kafka:3.7.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  stats-clickhouse:
    image: clickhouse/clickhouse-server:24.8
    environment:
      CLICKHOUSE_DB: stats
    ports:
      - "8123:8123"
      - "9000:9000"

  stats-service:
    build:
      context: .
      dockerfile: ./stats-service/Dockerfile
    environment:
      CLICKHOUSE_ADDR: stats-clickhouse:9000
      CLICKHOUSE_DB: stats
      KAFKA_BROKERS: kafka:9092
      KAFKA_VIEWS_TOPIC: post_views
      KAFKA_LIKES_TOPIC: post_likes
    depends_on:
      kafka:
        condition: service_started
      stats-clickhouse:
        condition: service_started
    ports:
      - "8081:8081"
